name = "SMLMDriftCorrection"
uuid = "34bda2d1-2fff-475a-a8c4-7f53d4251312"
authors = ["klidke@unm.edu"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
SMLMData = "5488f106-40b8-4660-84c5-84a168990d1b"
SMLMSim = "5a0a87e4-02d4-41f5-bf26-b8c94c784a04"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
BenchmarkTools = "1"
ForwardDiff = "0.10"
NearestNeighbors = "0.4"
Optim = "1"
PlotlyJS = "0.18"
ProfileView = "1"
SMLMData = "0.1"
SMLMSim = "0.1"
Statistics = "1"
Zygote = "0.6"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
