name = "SMLMDriftCorrection"
uuid = "34bda2d1-2fff-475a-a8c4-7f53d4251312"
version = "0.1.0"
authors = ["klidke@unm.edu"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FourierTools = "b18b359b-aebc-45ac-a139-9c0ccbb2871e"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LegendrePolynomials = "3db4a2ba-fc88-11e8-3e01-49c72059a882"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
SMLMData = "5488f106-40b8-4660-84c5-84a168990d1b"
SMLMSim = "5a0a87e4-02d4-41f5-bf26-b8c94c784a04"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
Distributions = "0.25"
FileIO = "1"
FourierTools = "0.4"
JLD2 = "0.4.54, 0.6"
LegendrePolynomials = "0.4"
MAT = "0.10.7, 0.11"
NearestNeighbors = "0.4"
Optim = "1"
SMLMData = "0.3, 0.4, 0.6"
SMLMSim = "0.3"
Statistics = "1"
StatsFuns = "1"
julia = "1.6"

[extras]
SMLMSim = "5a0a87e4-02d4-41f5-bf26-b8c94c784a04"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SMLMSim"]
