name = "SMLMDriftCorrection"
uuid = "34bda2d1-2fff-475a-a8c4-7f53d4251312"
authors = ["klidke@unm.edu"]
version = "0.1.0"

[deps]
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
SMLMData = "5488f106-40b8-4660-84c5-84a168990d1b"
SMLMSim = "5a0a87e4-02d4-41f5-bf26-b8c94c784a04"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
