[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FourierTools = "b18b359b-aebc-45ac-a139-9c0ccbb2871e"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SMLMData = "5488f106-40b8-4660-84c5-84a168990d1b"
SMLMDriftCorrection = "34bda2d1-2fff-475a-a8c4-7f53d4251312"
SMLMSim = "5a0a87e4-02d4-41f5-bf26-b8c94c784a04"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
