[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SMLMData = "5488f106-40b8-4660-84c5-84a168990d1b"
SMLMSim = "5a0a87e4-02d4-41f5-bf26-b8c94c784a04"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
