[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
SMLMData = "5488f106-40b8-4660-84c5-84a168990d1b"
SMLMDriftCorrection = "34bda2d1-2fff-475a-a8c4-7f53d4251312"
SMLMRender = "d945b928-cd23-4282-89d9-fc086b52682d"
SMLMSim = "5a0a87e4-02d4-41f5-bf26-b8c94c784a04"

[compat]
Documenter = "1"
